### PR TITLE
update ruby version to 2.3.0

### PR DESCRIPTION
**Pull request by jsugarman**

### CODE REVIEW

**Comment by novotnyjakub** [comment]
I'd upgrade to the latest patch - `2.3.1`.

Also I know it's been there for a while, but maybe we should keep the version either in the Gemfile, or in the dot file?

**Comment by jsugarman** [comment]
thanks, but it is in the Gemfile and .rvm, and docker and circle file

**Comment by novotnyjakub** [comment]
RVM can read version from the Gemfile as well, so there's no need for it. And Circle CI infers Ruby version from either. 
I thought it would be better not to maintain them separately to make sure we have only 1 version being used, if somebody missed to update one of them.

**Comment by jsugarman** [comment]
ok, I'll get rid of the .rvm file

**Comment by novotnyjakub** [comment]
Cool. The Ruby version is still running with security vulnerabilities, though..

**Pull request closed without merging**
