### PR TITLE
Made sure the label doesn't overrun on team dropdown

### PR DESCRIPTION
**Pull request by cfq**
Also added LoDash.

### CODE REVIEW

**Comment by fordie** [comment]
code looks ok to me, and has the desired effect on long departments. However, the Travis error makes me a bit twitchy about merging this in. I *think* it's ok as it appears to be something to do with the old dummy app. @threedaymonk can you confirm?

**Comment by threedaymonk** [comment]
@fordie I think that's just because it's based on the point before I fixed the Travis configuration. If you rebase this onto `origin/master`, it should pass.

**Comment by threedaymonk** [comment]
@fordie I have rebased it, so let's see if this works.

**Comment by threedaymonk** [comment]
I also suggest squashing these two commits together before merging.

**Pull request merged**
