### PR TITLE
Kill the engine

### PR DESCRIPTION
**Pull request by threedaymonk**
ET HIC DEFVNCTVS EST

1024px-tapestry_by_unknown_weaver_-_the_bayeux_tapestry_ detail _-_wga24166

It all seems to work just fine. The only remaining piece of work is to write a migration to munge the audit trail YAML yet again, to remove the `Peoplefinder::` prefix from the class names.

Enjoy the weekend @jaikoo, @cfq, @Najaf, @fordie!

### CODE REVIEW

**Comment by jaikoo** [comment]
Sweet!! Best news all year!!!

**Comment by Najaf** [comment]
Flawless Victory

**Comment by Najaf** [comment]
I am incredibly happy about this. Laughing babies and rainbow unicorns frolicking the meadow happy. Shall I push the button? Because I'll push the button. The sooner we merge this, the better, so I vote for merging right now. Someone better push the button or I'm totes pushing the button.

**Comment by ashb** [comment]
Are GDS no longer using this engine then?

**Comment by threedaymonk** [comment]
@ashb Not as far as we know. We don't have any ongoing contact, the people that were working on it aren't, and there hasn't been any work on [their repository](https://github.com/alphagov/gds-peoplefinder) since early December.

Of course, they are still able to fork the repository at any point prior to this merge, or to fork this repository and make their own customisations.

**Comment by threedaymonk** [comment]
As @ashb pointed out to me, this isn't a very helpful pull request: whilst everyone on the team knows the context, it's not expressed here. So here's an attempt to rectify that.

The original intention of the engine was to provide a core that both MOJ and GDS could use for their respective implementations, with differences in configuration, styling, and vocabulary. However, this benefit has not been realised because GDS have stopped working on it. Without any other consumers of the engine, it has, in fact, ended up growing MOJ-specific.

At the same time, developing against the engine has been a drag on productivity by adding a number of manual steps to development and deployment that were time-consuming and error-prone.

Finally, we believe that customisation needs can better be implemented using the environment, the database, feature flags and sub-locales.

**Pull request merged**
