### PR TITLE
Upgrade to work with 4.2.0rc1

### PR DESCRIPTION
**Pull request by Najaf**
@threedaymonk @novotnyjakub 

As per deprecation warnings, all calls to `deliver` have been changed to `deliver_now` or `deliver_later`, so we're automatically integrated with ActiveJob.

I've silenced some deprecation warnings:

* Using `_path` instead of `_url` helpers anywhere in an `ActionMailer` appears to trigger a warnings. We pass a `desired_path` around in parameters, which is probably vulnerable to an open redirect, but also isn't the failure mode this deprecation warning is trying to guard us against, so I ignored it.
* The other two appeared to be from library code that hasn't been fixed yet.

Silencing deprecations that we either can't fix or will probably be fixed by libraries later just feels horrible. It's problematic to do this from the engine because it's silencing them for wrapper applications too. Any suggestions for how to make this nicer would be appreciated.

## Why I didn't backport

`activejob_backport` doesn't implement the `deliver_later` integration with `ActionMailer`. My options then were to:

1. Re-implement `deliver_later`, and have to subsequently remove that implementation once we upgraded.
2. Create jobs or a generic job and change all instances of `deliver` to use it (the same or more amount of work as 1).

Since we're at rc1, I figured it would be less work overall just to go ahead with the upgrade.

Any feedback welcome!

### CODE REVIEW

**Comment by threedaymonk** [comment]
Is this pull request still relevant?

**Comment by Najaf** [comment]
I think so, we should assign someone to e.g. ensures test pass, merge master back into it and push for the merge. I can pick this up when I'm back on the team next week if no one else does.

**Comment by novotnyjakub** [comment]
We still need `ActiveJob`, but with the changes done between and the fact that there's a '4.2' stable Rails now, maybe it'll be easier to start over..

**Comment by Najaf** [comment]
Also re this:

> The desired path I think we should revisit completely. The code is very shady and over complicated, I think.

Agree wholeheartedly. It would be good to get this fixed before we move off this project.

**Comment by threedaymonk** [comment]
Closing as we're going to start over with 4.2.0.

**Pull request closed without merging**
