### PR TITLE
set db for testing

### PR DESCRIPTION
**Pull request by koikonom**

### CODE REVIEW

**Comment by jaikoo** [comment]
@threedaymonk & @koikonom  sanity check please

**Comment by threedaymonk** [comment]
I think `development` should probably be analogous (as otherwise the health check won't work in development). I don't think it needs to check the environment, though. In fact, I'm not sure the `test` configuration does, either.

**Comment by jaikoo** [comment]
@threedaymonk good point. Dev now works the same as test and prod.

**Comment by threedaymonk** [comment]
Hmm. We might need to revisit this: it makes it impossible to develop against a local PostgreSQL server with peer authentication.

**Pull request merged**
