### PR TITLE
Info labels

### PR DESCRIPTION
**Pull request by cfq**
Trello card: https://trello.com/c/vqxDOJXG/79-s-as-someone-looking-at-a-profile-i-need-context-so-that-i-can-understand-what-the-information-is-on-someone-s-profile

### CODE REVIEW

**Comment by novotnyjakub** [comment]
I checked it locally, it doesn't look right:

screen shot 2015-02-05 at 17 10 58

Looks like:
* The font size in general doesn't match the desing
* Role and team is not displayed correctly
* Additional Information and Skills have wrong label size
* Spacing between the lines also doesn't seem to match

**Comment by Najaf** [comment]
Apologies if it's been mentioned elsewhere but what's going on with this work? Something I can help with?

**Comment by cfq** [comment]
@novotnyjakub one last look?

**Comment by novotnyjakub** [comment]
screen shot 2015-02-20 at 16 03 27

**Comment by cfq** [comment]
Here is what it looks like right now.

screen shot 2015-02-25 at 14 20 21

**Comment by novotnyjakub** [comment]
That looks pretty good now, I think. Only the 'Additional information' should be 'Extra information:'. 

Could you please rebase on master and integrate with @threedaymonk latest changes for the phone numbers?

**Pull request merged**
